In [1]:
#first feature
weather=['Sunny','Sunny','Overcast','Rainy','Rainy','Rainy','Overcast','Sunny','Sunny',
        'Rainy','Sunny','Overcast','Overcast','Rainy']

In [2]:
#second feature
temp=['Hot','Hot','Hot','Mild','Cool','Cool','Cool','Mild','Cool','Mild','Mild',
     'Mild','Hot','Mild']

In [3]:
#Label or target variable
play=['No','No','Yes','Yes','Yes','No','Yes','No','Yes','Yes','Yes','Yes','Yes',
     'No']

In [5]:
#Import Label encoder
from sklearn import preprocessing

<frozen importlib._bootstrap>:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject


In [6]:
#creating labelEncoder
le=preprocessing.LabelEncoder()

In [7]:
weather_encoded=le.fit_transform(weather)

In [8]:
weather_encoded  # sunny2   Rainy1  Overcast0

array([2, 2, 0, 1, 1, 1, 0, 2, 2, 1, 2, 0, 0, 1], dtype=int64)

In [9]:
temp_encoded=le.fit_transform(temp)

In [11]:
temp_encoded   #Hot1 Mild2 Cool0

array([1, 1, 1, 2, 0, 0, 0, 2, 0, 2, 2, 2, 1, 2], dtype=int64)

In [12]:
play_encoded=le.fit_transform(play)

In [15]:
#combine two features
feature=list(zip(weather_encoded,temp_encoded))
feature

[(2, 1),
 (2, 1),
 (0, 1),
 (1, 2),
 (1, 0),
 (1, 0),
 (0, 0),
 (2, 2),
 (2, 0),
 (1, 2),
 (2, 2),
 (0, 2),
 (0, 1),
 (1, 2)]

In [16]:
from sklearn.neighbors import KNeighborsClassifier

In [17]:
model=KNeighborsClassifier(n_neighbors=3)

In [18]:
#train model
model.fit(feature,play_encoded)

KNeighborsClassifier(n_neighbors=3)

In [19]:
predicted=model.predict([[0,2]])

In [21]:
predicted

array([1], dtype=int64)